name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set environment variables
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "JWT_CLAIM_KEY=${{ secrets.JWT_CLAIM_KEY }}" >> $GITHUB_ENV 
          echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> $GITHUB_ENV 
          echo "RDS_JDBC=${{ secrets.RDS_JDBC }}" >> $GITHUB_ENV 
          echo "RDS_USERNAME=${{ secrets.RDS_USERNAME }}" >> $GITHUB_ENV 
          echo "GOOGLE_APP_PASSWORD=${{ secrets.GOOGLE_APP_PASSWORD }}" >> $GITHUB_ENV 
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV 
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV 

      - name: Grant to Gradlew
        run: chmod +x ./gradlew

      - name: Clean with Gradle
        run: ./gradlew clean

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t q1q1w2w2/wallet-keeper .

      - name: Push Docker Image
        run: |
          docker push q1q1w2w2/wallet-keeper

      - name: Deploy to EC2 (Switch Nginx)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull q1q1w2w2/wallet-keeper
            
            CURRENT_PORT=$(sudo grep -oP 'server 127\.0\.0\.1:\K[0-9]+' /etc/nginx/conf.d/wallet-keeper.conf)
            
            if [ "$CURRENT_PORT" = "8084" ]; then
              TARGET_COLOR="blue"
              TARGET_PORT="8083"
              CURRENT_COLOR="green"
            else
              TARGET_COLOR="green"
              TARGET_PORT="8084"
              CURRENT_COLOR="blue"
            fi
             
            echo "현재 연결된 포트: $CURRENT_PORT"
            echo "새로 연결할 포트: $TARGET_PORT ($TARGET_COLOR)"
            
            JWT_CLAIM_KEY="${{ secrets.JWT_CLAIM_KEY }}"
            JWT_SECRET="${{ secrets.JWT_SECRET }}"
            EC2_HOST="${{ secrets.EC2_HOST }}"
            RDS_JDBC="${{ secrets.RDS_JDBC }}"
            RDS_USERNAME="${{ secrets.RDS_USERNAME }}"
            RDS_PASSWORD="${{ secrets.RDS_PASSWORD }}"
            GOOGLE_APP_PASSWORD="${{ secrets.GOOGLE_APP_PASSWORD }}"
            GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"
            GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"
            GOOGLE_EMAIL="${{ secrets.GOOGLE_EMAIL }}"
            
            docker run -d --name wallet-keeper-$TARGET_COLOR -p $TARGET_PORT:8083 \
              -e JWT_CLAIM_KEY="${JWT_CLAIM_KEY}" \
              -e JWT_SECRET="${JWT_SECRET}" \
              -e EC2_HOST="${EC2_HOST}" \
              -e RDS_JDBC="${RDS_JDBC}" \
              -e RDS_USERNAME="${RDS_USERNAME}" \
              -e RDS_PASSWORD="${RDS_PASSWORD}" \
              -e GOOGLE_APP_PASSWORD="${GOOGLE_APP_PASSWORD}" \
              -e GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}" \
              -e GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET}" \
              -e GOOGLE_EMAIL="${GOOGLE_EMAIL}" \
              q1q1w2w2/wallet-keeper:latest
            
            sudo sed -i "s/$CURRENT_PORT/$TARGET_PORT/" /etc/nginx/conf.d/wallet-keeper.conf
            sudo nginx -s reload 
            
            docker ps -q -f "name=wallet-keeper-$CURRENT_COLOR" | grep -q . && docker stop wallet-keeper-$CURRENT_COLOR && docker rm wallet-keeper-$CURRENT_COLOR || true
            
            docker container prune -f
            docker rmi $(docker images -q -f "dangling=true") || true
